CREATE TABLE EMP (EMPNO BIGINT, ENAME VARCHAR(32), JOB VARCHAR(32), MGR BIGINT, HIREDATE DATE, SAL DECIMAL(10,2), COMM DECIMAL(10,2), DEPTNO BIGINT);
CREATE TABLE BONUS (ENAME VARCHAR(32), JOB VARCHAR(32), SAL DECIMAL(10,2), COMM DECIMAL(10,2));
