CREATE TABLE EMP (EMPNO BIGINT, ENAME STRING, JOB STRING, MGR BIGINT, HIREDATE DATE, SAL DECIMAL(10,2), COMM DECIMAL(10,2), DEPTNO BIGINT) USING parquet;
CREATE TABLE BONUS (ENAME STRING, JOB STRING, SAL DECIMAL(10,2), COMM DECIMAL(10,2)) USING parquet;
