CREATE TABLE `date_dim` (
  `d_date_sk` int NOT NULL,
  `d_date_id` char(16) NOT NULL,
  `d_date` date NOT NULL,
  `d_month_seq` int DEFAULT NULL,
  `d_week_seq` int DEFAULT NULL,
  `d_quarter_seq` int DEFAULT NULL,
  `d_year` int DEFAULT NULL,
  `d_dow` int DEFAULT NULL,
  `d_moy` int DEFAULT NULL,
  `d_dom` int DEFAULT NULL,
  `d_qoy` int DEFAULT NULL,
  `d_fy_year` int DEFAULT NULL,
  `d_fy_quarter_seq` int DEFAULT NULL,
  `d_fy_week_seq` int DEFAULT NULL,
  `d_day_name` char(9) DEFAULT NULL,
  `d_quarter_name` char(6) DEFAULT NULL,
  `d_holiday` char(1) DEFAULT NULL,
  `d_weekend` char(1) DEFAULT NULL,
  `d_following_holiday` char(1) DEFAULT NULL,
  `d_first_dom` int DEFAULT NULL,
  `d_last_dom` int DEFAULT NULL,
  `d_same_day_ly` int DEFAULT NULL,
  `d_same_day_lq` int DEFAULT NULL,
  `d_current_day` char(1) DEFAULT NULL,
  `d_current_week` char(1) DEFAULT NULL,
  `d_current_month` char(1) DEFAULT NULL,
  `d_current_quarter` char(1) DEFAULT NULL,
  `d_current_year` char(1) DEFAULT NULL,
  PRIMARY KEY (`d_date_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `item` (
  `i_item_sk` int NOT NULL,
  `i_item_id` char(16) NOT NULL,
  `i_rec_start_date` date DEFAULT NULL,
  `i_rec_end_date` date DEFAULT NULL,
  `i_item_desc` varchar(200) DEFAULT NULL,
  `i_current_price` decimal(7,2) DEFAULT NULL,
  `i_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `i_brand_id` int DEFAULT NULL,
  `i_brand` char(50) DEFAULT NULL,
  `i_class_id` int DEFAULT NULL,
  `i_class` char(50) DEFAULT NULL,
  `i_category_id` int DEFAULT NULL,
  `i_category` char(50) DEFAULT NULL,
  `i_manufact_id` int DEFAULT NULL,
  `i_manufact` char(50) DEFAULT NULL,
  `i_size` char(20) DEFAULT NULL,
  `i_formulation` char(20) DEFAULT NULL,
  `i_color` char(20) DEFAULT NULL,
  `i_units` char(10) DEFAULT NULL,
  `i_container` char(10) DEFAULT NULL,
  `i_manager_id` int DEFAULT NULL,
  `i_product_name` char(50) DEFAULT NULL,
  PRIMARY KEY (`i_item_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `store` (
  `s_store_sk` int NOT NULL,
  `s_store_id` char(16) NOT NULL,
  `s_rec_start_date` date DEFAULT NULL,
  `s_rec_end_date` date DEFAULT NULL,
  `s_closed_date_sk` int DEFAULT NULL,
  `s_store_name` varchar(50) DEFAULT NULL,
  `s_number_employees` int DEFAULT NULL,
  `s_floor_space` int DEFAULT NULL,
  `s_hours` char(20) DEFAULT NULL,
  `s_manager` varchar(40) DEFAULT NULL,
  `s_market_id` int DEFAULT NULL,
  `s_geography_class` varchar(100) DEFAULT NULL,
  `s_market_desc` varchar(100) DEFAULT NULL,
  `s_market_manager` varchar(40) DEFAULT NULL,
  `s_division_id` int DEFAULT NULL,
  `s_division_name` varchar(50) DEFAULT NULL,
  `s_company_id` int DEFAULT NULL,
  `s_company_name` varchar(50) DEFAULT NULL,
  `s_street_number` varchar(10) DEFAULT NULL,
  `s_street_name` varchar(60) DEFAULT NULL,
  `s_street_type` char(15) DEFAULT NULL,
  `s_suite_number` char(10) DEFAULT NULL,
  `s_city` varchar(60) DEFAULT NULL,
  `s_county` varchar(30) DEFAULT NULL,
  `s_state` char(2) DEFAULT NULL,
  `s_zip` char(10) DEFAULT NULL,
  `s_country` varchar(20) DEFAULT NULL,
  `s_gmt_offset` decimal(5,2) DEFAULT NULL,
  `s_tax_precentage` decimal(5,2) DEFAULT NULL,
  PRIMARY KEY (`s_store_sk`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `store_sales` (
  `ss_sold_date_sk` int DEFAULT NULL,
  `ss_sold_time_sk` int DEFAULT NULL,
  `ss_item_sk` int NOT NULL,
  `ss_customer_sk` int DEFAULT NULL,
  `ss_cdemo_sk` int DEFAULT NULL,
  `ss_hdemo_sk` int DEFAULT NULL,
  `ss_addr_sk` int DEFAULT NULL,
  `ss_store_sk` int DEFAULT NULL,
  `ss_promo_sk` int DEFAULT NULL,
  `ss_ticket_number` int NOT NULL,
  `ss_quantity` int DEFAULT NULL,
  `ss_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `ss_list_price` decimal(7,2) DEFAULT NULL,
  `ss_sales_price` decimal(7,2) DEFAULT NULL,
  `ss_ext_discount_amt` decimal(7,2) DEFAULT NULL,
  `ss_ext_sales_price` decimal(7,2) DEFAULT NULL,
  `ss_ext_wholesale_cost` decimal(7,2) DEFAULT NULL,
  `ss_ext_list_price` decimal(7,2) DEFAULT NULL,
  `ss_ext_tax` decimal(7,2) DEFAULT NULL,
  `ss_coupon_amt` decimal(7,2) DEFAULT NULL,
  `ss_net_paid` decimal(7,2) DEFAULT NULL,
  `ss_net_paid_inc_tax` decimal(7,2) DEFAULT NULL,
  `ss_net_profit` decimal(7,2) DEFAULT NULL,
  PRIMARY KEY (`ss_item_sk`,`ss_ticket_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

