#!/usr/bin/env bash
set -euo pipefail

source "$PWD/scripts/env_mysql.sh"

mysql -h "$MYSQL_HOST" -P "$MYSQL_PORT" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" <<'SQL'
DROP TABLE IF EXISTS EMP;
DROP TABLE IF EXISTS DEPT;

CREATE TABLE DEPT (
  DEPTNO INT NOT NULL PRIMARY KEY,
  NAME TEXT NOT NULL
);

CREATE TABLE EMP (
  EMPNO INT NOT NULL PRIMARY KEY,
  DEPTNO INT NOT NULL,
  ENAME TEXT NOT NULL,
  JOB TEXT NOT NULL,
  MGR INT,
  HIREDATE DATE NOT NULL,
  SAL INT NOT NULL,
  COMM INT NOT NULL,
  SLACKER BOOLEAN NOT NULL
);

INSERT INTO DEPT (DEPTNO, NAME) VALUES
  (10, 'Sales'),
  (20, 'IT');

INSERT INTO EMP (EMPNO, DEPTNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, SLACKER) VALUES
  (1, 10, 'Alice', 'CLERK',   100, '2020-01-01', 1000, 10, 1),
  (2, 10, 'Bob',   'CLERK',   100, '2020-01-02', 1100, 10, 1),
  (3, 10, 'Carol', 'ANALYST', 100, '2020-01-03', 1200, 10, 0),
  (4, 20, 'Dave',  'CLERK',   100, '2020-01-04', 1300, 10, 0),
  (5, 20, 'Eve',   'MANAGER', 100, '2020-01-05', 1400, 10, 0);

SELECT 'dept' AS table_name, COUNT(*) AS row_count FROM DEPT;
SELECT 'emp'  AS table_name, COUNT(*) AS row_count FROM EMP;
SQL
