#!/usr/bin/env bash
set -euo pipefail

source "$PWD/scripts/env_postgres.sh"

psql -w -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -v ON_ERROR_STOP=1 <<'SQL'
DROP TABLE IF EXISTS EMP CASCADE;
DROP TABLE IF EXISTS DEPT CASCADE;

CREATE TABLE DEPT (
  DEPTNO INT NOT NULL PRIMARY KEY,
  NAME TEXT NOT NULL
);

CREATE TABLE EMP (
  EMPNO INT NOT NULL PRIMARY KEY,
  DEPTNO INT NOT NULL,
  ENAME TEXT NOT NULL,
  JOB TEXT NOT NULL,
  MGR INT,
  HIREDATE DATE NOT NULL,
  SAL INT NOT NULL,
  COMM INT NOT NULL,
  SLACKER BOOLEAN NOT NULL
);

INSERT INTO DEPT (DEPTNO, NAME) VALUES
  (10, 'Sales'),
  (20, 'IT');

INSERT INTO EMP (EMPNO, DEPTNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, SLACKER) VALUES
  (1, 10, 'Alice', 'CLERK',   100, DATE '2020-01-01', 1000, 10, TRUE),
  (2, 10, 'Bob',   'CLERK',   100, DATE '2020-01-02', 1100, 10, TRUE),
  (3, 10, 'Carol', 'ANALYST', 100, DATE '2020-01-03', 1200, 10, FALSE),
  (4, 20, 'Dave',  'CLERK',   100, DATE '2020-01-04', 1300, 10, FALSE),
  (5, 20, 'Eve',   'MANAGER', 100, DATE '2020-01-05', 1400, 10, FALSE);

SELECT 'dept', COUNT(*) FROM DEPT;
SELECT 'emp', COUNT(*) FROM EMP;
SQL
